TASK: 'seg'

DATA_DIR: 'data/train_images'
TRAIN_DF: 'data/train_processed.csv'
FOLD_DF: 'data/folds/seg_10fold_4.csv'
# PSEUDO_TRAIN_DF: 'pseudo-labels/train_pseudo_191004b.csv'
# PSEUDO_FOLD_DF: 'pseudo-labels/seg_pseudo_191007c_0.05.csv'
TRAIN_ALL: False
SAMPLER: 'stratified'

TRAIN_DIR: '_results/Unet_eff-b1_fold4'

PARALLEL: True
DEBUG_IMAGE: False
DEBUG: False
PRINT_EVERY: 10

TRAIN:
  BATCH_SIZE: 32
  NUM_WORKERS: 8
  NUM_EPOCHS: 80

EVAL:
  BATCH_SIZE: 64
  NUM_WORKERS: 8

DATA:
  IMG_H: 256
  IMG_W: 1600

MODEL:
  ARCHITECTURE: 'Unet'
  ENCODER: 'efficientnet-b1'

LOSS:
  NAME: 'bce'
  FINETUNE_EPOCH: 15
  FINETUNE_LOSS: 'binary_lovasz_loss'

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001
  PARAMS:

SCHEDULER:
  NAME: 'multi_step'
  PARAMS:
    milestones: [5,30]
    gamma: 0.1
